- name: nginx install and Run 
  hosts: frontend
  become: yes # This playbook requires root privileges
  tasks:
    - name: install ngnix server
      ansible.builtin.package:
        name: nginx
        state: present
    - name: strart nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes