- name: Play 1
  hosts: local
  connection: local
  tasks:
    - name : hello from play 1 and task 1 
      ansible.builtin.debug:
        msg: "Hello from Play-1 and Task-1"

    - name: hello from play 1 and task 2 
      ansible.builtin.debug:
        msg: "Hello from play-1 and task-2"    

- name : Play 2
  hosts: local 
  connection: local 
  tasks:
    - name: hello from play-2 and task-1 
      ansible.builtin.debug:
        msg: "Hello Play-2 and Task-1"

    - name: hello from play-2 and task-2
      ansible.builtin.debug:
        msg: "Hello Play-2 and Task-2"        