- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Enter the user name
    private: true
      
  - name: PASSWORD
    prompt: Enter the password
    private: true
  tasks:  
    - name: printing user information
      ansible.builtin.debug:
        msg: "Hello {{ username }}. Your password is {{ PASSWORD }}."
      
  vars_prompt:
  - NUMBER: Enter a number
  - name: number
    prompt: Enter the number
    private: true 
  tasks:
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than or equal to 100"
    when: NUMBER <= 100

  - name: print if the number is greater than 100 
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER}}is greater than 100"
    when: NUMBER > 100
  
  - name: print if the number is even
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is even"
    when: NUMBER % 2 == 0

  - name: print if the number is odd  
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is odd"
    when: NUMBER % 2 != 0