- name: variables from inventory
  # This playbook uses variables defined in the inventory file
  hosts: local 
  connection: local
  tasks: 
    - name: print course info 
      ansible.builtin.debug:
        msg: "Hello i am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is : {{ TRAINER }}"

