- name: variables from inventory
  hosts: frontend
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE_NAME }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"