- name: Understand vars preferences
  hosts: local
  connection: local 
  vars:
    GREETING: "Hello from play "
  vars files:
    - course.yaml
  vars_prompt:
  - name: GREETING
    prompt: "Enter a greeting message"
    private: no
  tasks:
  - name : print the greeting
    # vars:
    # GREETING: "Hello from task"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"
        

# 1. command line or args
# 2. Task
# 3. File
# 4. prompt
# 5. Play
# 6. inventory