- name: loops in ansible
  hosts: local 
  connection: local
  tasks:
  - name: print numbers from 1 to 10
    ansible.builtin.debug:
      msg: "NUMBER: {{ item}}" # item is a loop variable
    loop: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10